In [1]:
import numpy as np

In [2]:
data = np.array([1,2,3,4,5])
data_2d = np.array([[1,2,3],[1,2,6]])
data_random = np.random.randn(2,3)
data_zeros = np.zeros(5)
data_ones = np.ones((2,3))

In [3]:
print(data)
print(data_2d)
print(data_random)
print(data_zeros)
print(data_ones)

[1 2 3 4 5]
[[1 2 3]
 [1 2 6]]
[[ 1.29174639 -0.08445739 -0.89542767]
 [-1.11522535 -0.00935516  1.94628906]]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [4]:
data = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [5]:
print(data)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
print(data[0,1])

2


In [7]:
print(data[0][1])

2


In [8]:
print(data[0][1:])

[2 3]


In [9]:
data[0]=100

In [10]:
data

array([[100, 100, 100],
       [  4,   5,   6],
       [  7,   8,   9]])

In [11]:
data[:]=300
data

array([[300, 300, 300],
       [300, 300, 300],
       [300, 300, 300]])

In [13]:
import pandas as pd
obj = pd.Series([10,20,30,40,50])
obj_2 = pd.Series([10,20,30,40,50],index = ['a','b','c','d','e'])

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [14]:
print(obj)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [15]:
print(obj.index)

RangeIndex(start=0, stop=5, step=1)


In [16]:
print(obj.values)

[10 20 30 40 50]


In [18]:
print(obj[1])

20


In [19]:
print(obj_2)

a    10
b    20
c    30
d    40
e    50
dtype: int64


In [21]:
print(obj_2[['a','e']])

a    10
e    50
dtype: int64


In [22]:
print(obj_2[1:3])

b    20
c    30
dtype: int64


In [24]:
data = {"이름":['유재석','박명수','정형돈','하하'],
       "나이":[35,60,52,38],
       '키':[180,175,160,150]}
frame= pd.DataFrame(data,index = ['첫째','둘째','셋째','넷째'])
print(frame)

     이름  나이    키
첫째  유재석  35  180
둘째  박명수  60  175
셋째  정형돈  52  160
넷째   하하  38  150


In [25]:
print(frame.loc['둘째','이름'])

박명수


In [26]:
print(frame.loc['넷째',['나이','키']])

나이     38
키     150
Name: 넷째, dtype: object


In [27]:
print(frame.iloc[0,2])

180


In [28]:
print(frame.iloc[3,:2])

이름    하하
나이    38
Name: 넷째, dtype: object


In [29]:
print(frame.iloc[:,[0,2]])

     이름    키
첫째  유재석  180
둘째  박명수  175
셋째  정형돈  160
넷째   하하  150


In [32]:
rank = frame.sort_values(by='나이')
rank

이름  나이    키
첫째  유재석  35  180
넷째   하하  38  150
셋째  정형돈  52  160
둘째  박명수  60  175

In [35]:
frame_2 = frame.iloc[:,[1,2]]
total = frame_2.sum(axis=0)

In [36]:
total

나이    185
키     665
dtype: int64

In [38]:
avg= frame_2.mean(axis=0)
avg

나이     46.25
키     166.25
dtype: float64

    나이    키
첫째  35  180
둘째  60  175
셋째  52  160
넷째  38  150
